//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class COMPETENCIA
    {
        public COMPETENCIA()
        {
            this.COMPETENCIASEXIGIDAS = new HashSet<COMPETENCIASEXIGIDA>();
            this.PESSOACOMPETENCIAS = new HashSet<PESSOACOMPETENCIA>();
        }
    
        public long ID { get; set; }
        public string DESCRICAO { get; set; }
        public string OBSERVAO { get; set; }
        public Nullable<int> NIVEL { get; set; }
        public Nullable<byte> STATUS { get; set; }
    
        public virtual ICollection<COMPETENCIASEXIGIDA> COMPETENCIASEXIGIDAS { get; set; }
        public virtual ICollection<PESSOACOMPETENCIA> PESSOACOMPETENCIAS { get; set; }
    }
}
