//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRITERIOSPROJETOSCOMPARACO
    {
        public long ID { get; set; }
        public long IDCRITERIO { get; set; }
        public long IDPROJETOA { get; set; }
        public Nullable<long> IDPROJETOB { get; set; }
        public string COMPARACAO { get; set; }
    
        public virtual CRITERIO CRITERIO { get; set; }
        public virtual PROJETO PROJETOA { get; set; }
        public virtual PROJETO PROJETOB { get; set; }
    }
}
