//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRITERIOSPROJETOSRESULTADOLISTA
    {
        public long ID { get; set; }
        public long IDCRITERIOSPROJETOSRESULTADO { get; set; }
        public long IDPROJETO { get; set; }
        public string COMPARACAO { get; set; }
    
        public virtual CRITERIOSPROJETOSRESULTADO CRITERIOSPROJETOSRESULTADO { get; set; }
        public virtual PROJETO PROJETO { get; set; }
    }
}
