//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class CRITERIO
    {
        public CRITERIO()
        {
            this.CRITERIOSCOMPARACOES = new HashSet<CRITERIOSCOMPARACO>();
            this.CRITERIOSCOMPARACOES1 = new HashSet<CRITERIOSCOMPARACO>();
            this.CRITERIOSPROJETOSCOMPARACOES = new HashSet<CRITERIOSPROJETOSCOMPARACO>();
            this.CRITERIOSRESULTADOes = new HashSet<CRITERIOSRESULTADO>();
            this.CRITERIOSRESULTADOLISTAs = new HashSet<CRITERIOSRESULTADOLISTA>();
        }
    
        public long ID { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public Nullable<System.DateTime> DATACRIACAO { get; set; }
    
        public virtual ICollection<CRITERIOSCOMPARACO> CRITERIOSCOMPARACOES { get; set; }
        public virtual ICollection<CRITERIOSCOMPARACO> CRITERIOSCOMPARACOES1 { get; set; }
        public virtual ICollection<CRITERIOSPROJETOSCOMPARACO> CRITERIOSPROJETOSCOMPARACOES { get; set; }
        public virtual ICollection<CRITERIOSRESULTADO> CRITERIOSRESULTADOes { get; set; }
        public virtual ICollection<CRITERIOSRESULTADOLISTA> CRITERIOSRESULTADOLISTAs { get; set; }
    }
}
