//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbProjetosEntities : DbContext
    {
        public dbProjetosEntities()
            : base("name=dbProjetosEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<COMPETENCIA> COMPETENCIAS { get; set; }
        public virtual DbSet<COMPETENCIASEXIGIDA> COMPETENCIASEXIGIDAS { get; set; }
        public virtual DbSet<PERFILUSUARIO> PERFILUSUARIOs { get; set; }
        public virtual DbSet<PERMISSO> PERMISSOES { get; set; }
        public virtual DbSet<PESSOACOMPETENCIA> PESSOACOMPETENCIAS { get; set; }
        public virtual DbSet<PESSOA> PESSOAS { get; set; }
        public virtual DbSet<PROJETOSPESSOA> PROJETOSPESSOAS { get; set; }
        public virtual DbSet<REUNIOESPARTICIPANTE> REUNIOESPARTICIPANTES { get; set; }
        public virtual DbSet<USUARIO> USUARIOS { get; set; }
        public virtual DbSet<CRITERIO> CRITERIOS { get; set; }
        public virtual DbSet<CRITERIOSCOMPARACO> CRITERIOSCOMPARACOES { get; set; }
        public virtual DbSet<CRITERIOSPROJETOSCOMPARACO> CRITERIOSPROJETOSCOMPARACOES { get; set; }
        public virtual DbSet<CRITERIOSRESULTADO> CRITERIOSRESULTADOes { get; set; }
        public virtual DbSet<CRITERIOSRESULTADOLISTA> CRITERIOSRESULTADOLISTAs { get; set; }
        public virtual DbSet<CRITERIOSPROJETOSRESULTADO> CRITERIOSPROJETOSRESULTADOes { get; set; }
        public virtual DbSet<CRITERIOSPROJETOSRESULTADOLISTA> CRITERIOSPROJETOSRESULTADOLISTAs { get; set; }
        public virtual DbSet<RECEITAVARIAVEL> RECEITAVARIAVELs { get; set; }
        public virtual DbSet<PAUTARECEITAVARIAVEL> PAUTARECEITAVARIAVELs { get; set; }
        public virtual DbSet<PAUTAPROJETO> PAUTAPROJETOS { get; set; }
        public virtual DbSet<REUNIO> REUNIOES { get; set; }
        public virtual DbSet<PROJETO> PROJETOS { get; set; }
    }
}
