//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAUTARECEITAVARIAVEL
    {
        public long ID { get; set; }
        public long IDPAUTAPROJETO { get; set; }
        public Nullable<System.DateTime> DATAPERIODO { get; set; }
        public string TIPO { get; set; }
        public Nullable<System.DateTime> DATACRIACAO { get; set; }
        public Nullable<decimal> VALOR { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public string OBSERVACOES { get; set; }
    
        public virtual PAUTAPROJETO PAUTAPROJETO { get; set; }
    }
}
