//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAUTAPROJETO
    {
        public PAUTAPROJETO()
        {
            this.PAUTARECEITAVARIAVELs = new HashSet<PAUTARECEITAVARIAVEL>();
        }
    
        public long ID { get; set; }
        public long IDREUNIAO { get; set; }
        public long IDPROJETO { get; set; }
        public Nullable<decimal> TEMPOPREVISTOCONCLUSAO { get; set; }
        public Nullable<decimal> RECEITACONSTANTE { get; set; }
        public Nullable<decimal> RAZAORECEITAVALOR { get; set; }
        public Nullable<decimal> RAZAORECEITAPERCENTUAL { get; set; }
        public Nullable<decimal> INVESTIMENTOPREVISTO { get; set; }
        public Nullable<decimal> RESULTADOPAYBACK { get; set; }
        public Nullable<int> ORDEMRESULTADOPAYBACK { get; set; }
        public string APROVACAORESULTADOPAYBACK { get; set; }
        public Nullable<decimal> RESULTADOVALORPRESENTELIQUIDO { get; set; }
        public Nullable<int> ORDEMRESULTADOVALORPRESENTELIQUIDO { get; set; }
        public string APROVACAORESULTADOVALORPRESENTELIQUIDO { get; set; }
        public Nullable<decimal> RESULTADOTAXAINTERNARETORNO { get; set; }
        public Nullable<int> ORDEMRESULTADOTAXAINTERNARETORNO { get; set; }
        public string APROVACAORESULTADOTAXAINTERNARETORNO { get; set; }
        public Nullable<decimal> RESULTADODICE { get; set; }
        public Nullable<int> ORDEMRESULTADODICE { get; set; }
        public string APROVACAORESULTADODICE { get; set; }
        public Nullable<int> CAPACIDADEENTREGAEQUPE { get; set; }
        public Nullable<int> APOIOALTAGESTAO { get; set; }
        public Nullable<int> APOIOSTEAKHOLDERS { get; set; }
        public Nullable<int> ESFORCOADICIONAL { get; set; }
        public Nullable<decimal> RESULTADOAHP { get; set; }
        public Nullable<int> ORDEMRESULTADOAHP { get; set; }
        public string APROVACAORESULTADOAHP { get; set; }
    
        public virtual REUNIO REUNIO { get; set; }
        public virtual ICollection<PAUTARECEITAVARIAVEL> PAUTARECEITAVARIAVELs { get; set; }
        public virtual PROJETO PROJETO { get; set; }
    }
}
