//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERFILUSUARIO
    {
        public PERFILUSUARIO()
        {
            this.USUARIOS = new HashSet<USUARIO>();
        }
    
        public long ID { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATACRICAO { get; set; }
        public Nullable<byte> STATUS { get; set; }
    
        public virtual PERMISSO PERMISSO { get; set; }
        public virtual ICollection<USUARIO> USUARIOS { get; set; }
    }
}
