//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class PERMISSO
    {
        public long ID { get; set; }
        public string DESCRICAO { get; set; }
        public Nullable<System.DateTime> DATA_CRIACAO { get; set; }
    
        public virtual PERFILUSUARIO PERFILUSUARIO { get; set; }
    }
}
