//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJETO
    {
        public PROJETO()
        {
            this.COMPETENCIASEXIGIDAS = new HashSet<COMPETENCIASEXIGIDA>();
            this.CRITERIOSPROJETOSCOMPARACOES = new HashSet<CRITERIOSPROJETOSCOMPARACO>();
            this.CRITERIOSPROJETOSCOMPARACOES1 = new HashSet<CRITERIOSPROJETOSCOMPARACO>();
            this.CRITERIOSPROJETOSRESULTADOes = new HashSet<CRITERIOSPROJETOSRESULTADO>();
            this.CRITERIOSPROJETOSRESULTADOLISTAs = new HashSet<CRITERIOSPROJETOSRESULTADOLISTA>();
            this.PAUTAPROJETOS = new HashSet<PAUTAPROJETO>();
            this.PROJETOSPESSOAS = new HashSet<PROJETOSPESSOA>();
            this.RECEITAVARIAVELs = new HashSet<RECEITAVARIAVEL>();
        }
    
        public long ID { get; set; }
        public string NOME { get; set; }
        public string DESCRICAO { get; set; }
        public string OBSERVACAO { get; set; }
        public long GERENTE { get; set; }
        public Nullable<System.DateTime> DATACRIACAO { get; set; }
        public Nullable<decimal> INVESTIMENTOPREVISTO { get; set; }
        public Nullable<decimal> RECEITACONSTANTE { get; set; }
        public Nullable<decimal> RAZAORECEITAVALOR { get; set; }
        public Nullable<decimal> RAZAORECEITAPERCENTUAL { get; set; }
        public Nullable<decimal> TEMPOPREVISTOCONCLUSAO { get; set; }
        public Nullable<byte> STATUS { get; set; }
        public Nullable<int> CAPACIDADEENTREGAEQUIPE { get; set; }
        public Nullable<int> APOIOALTAGESTAO { get; set; }
        public Nullable<int> APOIOSTEAKHOLDERS { get; set; }
        public Nullable<int> ESFORCOADICIONAL { get; set; }
    
        public virtual ICollection<COMPETENCIASEXIGIDA> COMPETENCIASEXIGIDAS { get; set; }
        public virtual ICollection<CRITERIOSPROJETOSCOMPARACO> CRITERIOSPROJETOSCOMPARACOES { get; set; }
        public virtual ICollection<CRITERIOSPROJETOSCOMPARACO> CRITERIOSPROJETOSCOMPARACOES1 { get; set; }
        public virtual ICollection<CRITERIOSPROJETOSRESULTADO> CRITERIOSPROJETOSRESULTADOes { get; set; }
        public virtual ICollection<CRITERIOSPROJETOSRESULTADOLISTA> CRITERIOSPROJETOSRESULTADOLISTAs { get; set; }
        public virtual ICollection<PAUTAPROJETO> PAUTAPROJETOS { get; set; }
        public virtual PESSOA GERENTEPROJETO { get; set; }
        public virtual ICollection<PROJETOSPESSOA> PROJETOSPESSOAS { get; set; }
        public virtual ICollection<RECEITAVARIAVEL> RECEITAVARIAVELs { get; set; }
    }
}
