//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class PROJETOSPESSOA
    {
        public long ID { get; set; }
        public long IDPROJETO { get; set; }
        public Nullable<long> IDPESSOA { get; set; }
        public Nullable<System.DateTime> DATAINGRESSO { get; set; }
        public string OCUPACAO { get; set; }
        public string OBSERVACOES { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
        public virtual PROJETO PROJETO { get; set; }
    }
}
