//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class REUNIOESPARTICIPANTE
    {
        public long IDREUNIAO { get; set; }
        public long IDPESSOA { get; set; }
        public string OBSERVACAO { get; set; }
        public Nullable<byte> COMPARECIMENTO { get; set; }
        public Nullable<byte> STATUS { get; set; }
    
        public virtual PESSOA PESSOA { get; set; }
        public virtual REUNIO REUNIO { get; set; }
    }
}
