//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EFDados
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO
    {
        public long ID { get; set; }
        public string LOGIN { get; set; }
        public string PASSWORD { get; set; }
        public Nullable<long> PERFILUSUARIO { get; set; }
        public Nullable<System.DateTime> DATACRICAO { get; set; }
        public Nullable<byte> STATUS { get; set; }
    
        public virtual PERFILUSUARIO PERFILUSUARIO1 { get; set; }
    }
}
